version: 2
jobs:
 build:
   machine:
     image: ubuntu-1604:201903-01
   environment:
     DOCKER_BUILDKIT: 1
   steps:
     - checkout
     - run: docker version
     - run: docker build -t cmg-seafarers --progress plain .

